import React from "react";
import "./global.css";

const RootLayout = ({ children }: any) => {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="Generated by next app" />
        <title>NEXT-13</title>
      </head>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
