import Navbar from "../components/navbar/Navbar";
import "./global.css";

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="Generated by next app" />
        <title>NEXT-13</title>
      </head>
      <body>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
